"""Exact sign-flip permutation test over index-paired samples.

The test pairs ``x`` and ``y`` positionally over the shorter input and asks
whether the paired median percent delta could plausibly arise under the null
hypothesis of no effect. Under that null a paired observation is exchangeable
with its partner, so the null distribution is generated by flipping the sign of
each pair's difference: enumerated exhaustively when the ``2**pairs`` sign-flip
space fits the resample budget, and sampled with a fixed seed above it. Either
way the reported p-value is deterministic for a given input.
"""

import math
from collections.abc import Sequence

from gymrat_py.stats.descriptive import compute_median
from gymrat_py.stats.results import SignificanceResult, count_nonzero_pairs

# The permutation needs at least two paired observations; a single pair admits
# only the trivial sign flip and carries no null spread to test against.
_MIN_PAIRS = 2

RESAMPLE_BUDGET = 9999
"""Upper bound on sign-flip resamples.

When the exact null space ``2**pairs`` is at most this budget, every sign flip
is enumerated (exact test); above it, this many Monte Carlo resamples are drawn.
The value brackets the exact/Monte Carlo seam at ``pairs == 13``: ``2**13 ==
8192`` still enumerates exactly, while ``2**14 == 16384`` crosses into sampling.
"""

PERMUTATION_SEED = 12345
"""Fixed RNG seed for the Monte Carlo path, making sampled p-values reproducible."""


def _percent_delta(baseline: Sequence[float], candidate: Sequence[float]) -> float:
    """Return the median percent delta of ``candidate`` against ``baseline``.

    The functional is ``100 * (median(candidate) - median(baseline)) /
    abs(median(baseline))``. When the baseline median is zero the ratio is
    undefined, so this returns NaN rather than dividing by zero — callers treat
    a non-finite delta as "no direction to test".

    Args:
        baseline: The reference samples (non-empty).
        candidate: The samples compared against the baseline (non-empty).

    Returns:
        The percent delta, or ``float("nan")`` when the baseline median is zero.
    """
    base = compute_median(baseline)
    denom = abs(base)
    if denom == 0.0:
        return math.nan
    return 100.0 * (compute_median(candidate) - base) / denom


def sign_flip_permutation_test(x: Sequence[float], y: Sequence[float]) -> SignificanceResult:
    """Run a two-sided sign-flip permutation test on index-paired samples.

    The inputs are paired positionally over the shorter of the two: ``x[i]`` is
    compared with ``y[i]`` for ``i < min(len(x), len(y))``, and trailing entries
    of the longer input are ignored. The reported ``n`` counts only pairs whose
    difference is non-zero.

    The test statistic is the median percent delta of the paired slices,
    ``100 * (median(y) - median(x)) / abs(median(x))``; its permutation null
    distribution comes from flipping the sign of each pair's difference. When the
    ``2**pairs`` sign-flip space fits :data:`RESAMPLE_BUDGET` the enumeration is
    exact; otherwise :data:`RESAMPLE_BUDGET` Monte Carlo resamples are drawn from
    a generator seeded with :data:`PERMUTATION_SEED`. Both paths are
    deterministic for a given input.

    Degenerate inputs cannot support the test and short-circuit to a
    non-significant ``p = 1.0`` without invoking scipy: fewer than two pairs,
    all-zero paired differences, and a non-finite observed statistic (the
    baseline median is zero, so the percent delta is undefined).

    Args:
        x: The baseline sample.
        y: The candidate sample, paired positionally with ``x``.

    Returns:
        A :class:`SignificanceResult` whose ``p`` is the two-sided permutation
        p-value clamped to at most ``1.0`` and whose ``n`` is the number of
        non-zero paired differences.
    """
    m, n = count_nonzero_pairs(x, y)
    if n == 0 or m < _MIN_PAIRS:
        return SignificanceResult(p=1.0, n=n)

    x_paired = list(x[:m])
    y_paired = list(y[:m])

    observed = _percent_delta(x_paired, y_paired)
    if not math.isfinite(observed):
        return SignificanceResult(p=1.0, n=n)

    # Import lazily so importing ``gymrat_py.stats`` never pulls in scipy; see
    # tests/test_import_latency.py, which guards the package's startup cost.
    import numpy as np  # noqa: PLC0415
    from scipy.stats import permutation_test  # noqa: PLC0415

    def statistic(baseline: Sequence[float], candidate: Sequence[float]) -> float:
        # scipy passes numpy arrays; convert to lists so ``compute_median``'s
        # emptiness check (``if not values``) sees a plain sequence, not an
        # array whose truthiness is ambiguous.
        return _percent_delta(list(baseline), list(candidate))

    # ``m`` is the number of pairs scipy actually sign-flips, hence the exponent
    # of the null space. scipy enumerates exactly when ``n_resamples`` reaches
    # that space; otherwise it samples with the seeded generator.
    exact_space = 2**m
    n_resamples = min(exact_space, RESAMPLE_BUDGET)

    result = permutation_test(
        (x_paired, y_paired),
        statistic,
        permutation_type="samples",
        alternative="two-sided",
        vectorized=False,
        n_resamples=n_resamples,
        rng=np.random.default_rng(PERMUTATION_SEED),
    )
    return SignificanceResult(p=min(float(result.pvalue), 1.0), n=n)
