"""Exact sign-flip permutation test over index-paired samples.

The test pairs ``x`` and ``y`` positionally over the shorter input and asks
whether the paired median percent delta could plausibly arise under the null
hypothesis of no effect. Under that null a paired observation is exchangeable
with its partner, so the null distribution is generated by flipping the sign of
each pair's difference: enumerated exhaustively when the ``2**pairs`` sign-flip
space fits the resample budget, and sampled with a fixed seed above it. Either
way the reported p-value is deterministic for a given input.
"""

import math
from collections.abc import Callable, Sequence
from dataclasses import dataclass

from gymrat.stats.descriptive import compute_median


@dataclass(frozen=True, slots=True)
class SignificanceResult:
    """The outcome of a paired significance test.

    Attributes:
        p: The two-sided p-value, always within ``[0.0, 1.0]``.
        n: The number of paired entries whose difference is non-zero.  Tied
            pairs (zero difference) are held fixed on both sides — they
            contribute to medians under every rearrangement but are not
            sign-flipped.
    """

    p: float
    n: int


def count_nonzero_pairs(x: Sequence[float], y: Sequence[float]) -> tuple[int, int]:
    """Pair ``x`` and ``y`` positionally over the shorter input and count non-zero diffs.

    Shared by every paired significance test: each pairs ``x[i]`` with ``y[i]``
    for ``i`` below the shorter input's length.  The caller holds zero-difference
    (tied) pairs fixed on both sides of the test rather than dropping them.

    Args:
        x: The first sample.
        y: The second sample, paired positionally with ``x``.

    Returns:
        A ``(m, n)`` pair: ``m`` is the number of positions paired (the shorter
        input's length), and ``n`` is how many of those pairs have a non-zero
        difference.
    """
    pairs = list(zip(x, y, strict=False))
    n = sum(1 for xi, yi in pairs if xi - yi != 0)
    return len(pairs), n


# The permutation needs at least two paired observations; a single pair admits
# only the trivial sign flip and carries no null spread to test against.
_MIN_PAIRS = 2

RESAMPLE_BUDGET = 9999
"""Upper bound on sign-flip resamples.

When the exact null space ``2**pairs`` is at most this budget, every sign flip
is enumerated (exact test); above it, this many Monte Carlo resamples are drawn.
The value brackets the exact/Monte Carlo seam at ``pairs == 13``: ``2**13 ==
8192`` still enumerates exactly, while ``2**14 == 16384`` crosses into sampling.
"""

PERMUTATION_SEED = 12345
"""Fixed RNG seed for the Monte Carlo path, making sampled p-values reproducible."""


def _percent_delta(baseline: Sequence[float], candidate: Sequence[float]) -> float:
    """Return the median percent delta of ``candidate`` against ``baseline``.

    The functional is ``100 * (median(candidate) - median(baseline)) /
    abs(median(baseline))``.

    When the baseline median is zero the ratio is undefined.  Returns ``0.0``
    when both medians are zero (no separation) and ``NaN`` otherwise — the
    caller decides how to treat the undefined case (the permutation test's
    statistic closure converts it to signed infinity so scipy's null tally
    counts it on the correct tail).

    Args:
        baseline: The reference samples (non-empty).
        candidate: The samples compared against the baseline (non-empty).

    Returns:
        The percent delta, ``0.0`` when both medians are zero, or ``NaN``
        when only the baseline median is zero.
    """
    base = compute_median(baseline)
    denom = abs(base)
    if denom == 0.0:
        if compute_median(candidate) == base:
            return 0.0
        return math.nan
    return 100.0 * (compute_median(candidate) - base) / denom


def _partition_pairs(
    x: Sequence[float], y: Sequence[float], m: int
) -> tuple[list[float], list[float], list[float], list[float]]:
    """Separate tied (zero-diff) and differing pairs over the first ``m`` indices.

    Returns ``(tied_x, tied_y, diff_x, diff_y)``.
    """
    tied_x: list[float] = []
    tied_y: list[float] = []
    diff_x: list[float] = []
    diff_y: list[float] = []
    for xi, yi in zip(x[:m], y[:m], strict=True):
        if xi == yi:
            tied_x.append(xi)
            tied_y.append(yi)
        else:
            diff_x.append(xi)
            diff_y.append(yi)
    return tied_x, tied_y, diff_x, diff_y


def _make_statistic(
    tied_x: list[float],
    tied_y: list[float],
    observed: float,
) -> Callable[[Sequence[float], Sequence[float]], float]:
    """Build the test statistic closure for scipy's permutation_test."""

    def statistic(baseline: Sequence[float], candidate: Sequence[float]) -> float:
        delta = _percent_delta(tied_x + list(baseline), tied_y + list(candidate))
        if math.isnan(delta):
            return math.copysign(math.inf, observed)
        return delta

    return statistic


def sign_flip_permutation_test(x: Sequence[float], y: Sequence[float]) -> SignificanceResult:
    """Run a two-sided sign-flip permutation test on index-paired samples.

    The inputs are paired positionally over the shorter of the two: ``x[i]`` is
    compared with ``y[i]`` for ``i < min(len(x), len(y))``, and trailing entries
    of the longer input are ignored. The reported ``n`` counts only pairs whose
    difference is non-zero.

    Tied pairs (zero difference) are held fixed on both sides: they contribute
    to the median under every rearrangement but are never sign-flipped, so the
    effective null space is ``2**n`` where ``n`` is the differing-pair count.

    The test statistic is the median percent delta of the paired slices,
    ``100 * (median(y) - median(x)) / abs(median(x))``; its permutation null
    distribution comes from flipping the sign of each differing pair's
    difference. When ``2**n`` fits :data:`RESAMPLE_BUDGET` the enumeration is
    exact; otherwise :data:`RESAMPLE_BUDGET` Monte Carlo resamples are drawn from
    a generator seeded with :data:`PERMUTATION_SEED`. Both paths are
    deterministic for a given input.
    """
    m, n = count_nonzero_pairs(x, y)
    if n < _MIN_PAIRS:
        return SignificanceResult(p=1.0, n=n)

    tied_x, tied_y, diff_x, diff_y = _partition_pairs(x, y, m)

    observed = _percent_delta(tied_x + diff_x, tied_y + diff_y)
    if not math.isfinite(observed):
        return SignificanceResult(p=1.0, n=n)

    # Lazy import: tests/test_import_latency.py guards the package's startup cost.
    import numpy as np  # noqa: PLC0415
    from scipy.stats import permutation_test  # noqa: PLC0415

    n_resamples = min(2**n, RESAMPLE_BUDGET)
    result = permutation_test(
        (diff_x, diff_y),
        _make_statistic(tied_x, tied_y, observed),
        permutation_type="samples",
        alternative="two-sided",
        vectorized=False,
        n_resamples=n_resamples,
        rng=np.random.default_rng(PERMUTATION_SEED),
    )
    return SignificanceResult(p=min(float(result.pvalue), 1.0), n=n)
