"""Exact sign-flip permutation test over index-paired samples.

The test pairs ``x`` and ``y`` positionally over the shorter input and asks
whether the paired median percent delta could plausibly arise under the null
hypothesis of no effect. Under that null a paired observation is exchangeable
with its partner, so the null distribution is generated by flipping the sign of
each pair's difference: enumerated exhaustively when the ``2**pairs`` sign-flip
space fits the resample budget, and sampled with a fixed seed above it. Either
way the reported p-value is deterministic for a given input.
"""

import math
import statistics
from collections.abc import Callable, Sequence
from dataclasses import dataclass

from gymrat.stats.descriptive import percent_delta


@dataclass(frozen=True, slots=True)
class SignificanceResult:
    """The outcome of a paired significance test.

    Attributes:
        p: The two-sided p-value, always within ``[0.0, 1.0]``.
        n: The number of paired entries whose two values differ.  Tied
            pairs (equal values) are held fixed on both sides — they
            contribute to medians under every rearrangement but are not
            sign-flipped.
    """

    p: float
    n: int


def count_nonzero_pairs(x: Sequence[float], y: Sequence[float]) -> tuple[int, int]:
    """Pair ``x`` and ``y`` positionally over the shorter input and count differing pairs.

    Shared by every paired significance test: each pairs ``x[i]`` with ``y[i]``
    for ``i`` below the shorter input's length.  A pair is tied when its values
    compare equal (``x[i] == y[i]``) and differing otherwise, so a pair of equal
    infinities is tied and a pair holding a NaN always differs.  The caller holds
    tied pairs fixed on both sides of the test rather than dropping them.

    Args:
        x: The first sample.
        y: The second sample, paired positionally with ``x``.

    Returns:
        A ``(m, n)`` pair: ``m`` is the number of positions paired (the shorter
        input's length), and ``n`` is how many of those pairs have values that
        differ (``x[i] != y[i]``).
    """
    tied_x, _, diff_x, _ = _partition_pairs(x, y)
    return len(tied_x) + len(diff_x), len(diff_x)


# The permutation needs at least two paired observations; a single pair admits
# only the trivial sign flip and carries no null spread to test against.
_MIN_PAIRS = 2

RESAMPLE_BUDGET = 9999
"""Upper bound on sign-flip resamples.

When the exact null space ``2**pairs`` is at most this budget, every sign flip
is enumerated (exact test); above it, this many Monte Carlo resamples are drawn.
The value brackets the exact/Monte Carlo seam at ``pairs == 13``: ``2**13 ==
8192`` still enumerates exactly, while ``2**14 == 16384`` crosses into sampling.
"""

PERMUTATION_SEED = 12345
"""Fixed RNG seed for the Monte Carlo path, making sampled p-values reproducible."""


def _partition_pairs(
    x: Sequence[float], y: Sequence[float]
) -> tuple[list[float], list[float], list[float], list[float]]:
    """Separate tied (equal values) and differing pairs, paired over the shorter input.

    Args:
        x: The first value of each pair.
        y: The second value of each pair.

    Returns:
        A tuple ``(tied_x, tied_y, diff_x, diff_y)`` partitioning the pairs.
    """
    tied_x: list[float] = []
    tied_y: list[float] = []
    diff_x: list[float] = []
    diff_y: list[float] = []
    for xi, yi in zip(x, y, strict=False):
        if xi == yi:
            tied_x.append(xi)
            tied_y.append(yi)
        else:
            diff_x.append(xi)
            diff_y.append(yi)
    return tied_x, tied_y, diff_x, diff_y


def _median_delta(
    tied_x: list[float],
    tied_y: list[float],
    baseline: Sequence[float],
    candidate: Sequence[float],
) -> float:
    return percent_delta(
        statistics.median(tied_x + list(baseline)), statistics.median(tied_y + list(candidate))
    )


def _make_statistic(
    tied_x: list[float],
    tied_y: list[float],
    observed: float,
) -> Callable[[Sequence[float], Sequence[float]], float]:
    """Build the test statistic closure for scipy's permutation_test.

    An undefined delta (a zero baseline median) becomes infinity signed like
    ``observed``, so scipy's null tally counts it on the correct tail.

    Args:
        tied_x: Baseline values of the tied (equal-value) pairs, held fixed.
        tied_y: Candidate values of the tied (equal-value) pairs, held fixed.
        observed: The delta the samples produced in their original order.

    Returns:
        The statistic scipy evaluates on each rearrangement of the differing pairs.
    """

    def statistic(baseline: Sequence[float], candidate: Sequence[float]) -> float:
        delta = _median_delta(tied_x, tied_y, baseline, candidate)
        if math.isnan(delta):
            return math.copysign(math.inf, observed)
        return delta

    return statistic


def sign_flip_permutation_test(x: Sequence[float], y: Sequence[float]) -> SignificanceResult:
    """Run a two-sided sign-flip permutation test on index-paired samples.

    The inputs are paired positionally over the shorter of the two: ``x[i]`` is
    compared with ``y[i]`` for ``i < min(len(x), len(y))``, and trailing entries
    of the longer input are ignored. The reported ``n`` counts only pairs whose
    two values differ.

    Tied pairs (equal values) are held fixed on both sides: they contribute
    to the median under every rearrangement but are never sign-flipped, so the
    effective null space is ``2**n`` where ``n`` is the differing-pair count.

    The test statistic is the median percent delta of the paired slices,
    ``100 * (median(y) - median(x)) / abs(median(x))``; its permutation null
    distribution comes from flipping the sign of each differing pair's
    difference. When ``2**n`` fits :data:`RESAMPLE_BUDGET` the enumeration is
    exact; otherwise :data:`RESAMPLE_BUDGET` Monte Carlo resamples are drawn from
    a generator seeded with :data:`PERMUTATION_SEED`. Both paths are
    deterministic for a given input.

    Args:
        x: The baseline sample.
        y: The candidate sample, paired positionally with ``x``.

    Returns:
        The p-value and the count of differing pairs used.
    """
    tied_x, tied_y, diff_x, diff_y = _partition_pairs(x, y)
    n = len(diff_x)
    if n < _MIN_PAIRS:
        return SignificanceResult(p=1.0, n=n)

    observed = _median_delta(tied_x, tied_y, diff_x, diff_y)
    if not math.isfinite(observed):
        return SignificanceResult(p=1.0, n=n)

    # Lazy import: tests/test_import_latency.py guards the package's startup cost.
    import numpy as np  # noqa: PLC0415
    from scipy.stats import permutation_test  # noqa: PLC0415

    # scipy enumerates all 2**n sign flips itself whenever they fit the budget.
    result = permutation_test(
        (diff_x, diff_y),
        _make_statistic(tied_x, tied_y, observed),
        permutation_type="samples",
        alternative="two-sided",
        vectorized=False,
        n_resamples=RESAMPLE_BUDGET,
        rng=np.random.default_rng(PERMUTATION_SEED),
    )
    return SignificanceResult(p=float(result.pvalue), n=n)
