"""Markdown reference document generation from JSON schemas and reader specs.

Builds a human-readable Markdown document describing every record and event
type in the session log and supervisor log, with field tables, nested-object
subsections, and a closing Readers section.
"""

import json
import textwrap
from typing import Any

from gymrat.event_docs.asyncapi import (
    _MODEL_BY_NAME,
    SESSION_LOG_ADDRESS,
    SUPERVISOR_LOG_ADDRESS,
    ReaderSpec,
)
from gymrat.event_docs.asyncapi import (
    _docstring_first_line as _model_docstring_first_line,
)
from gymrat.event_docs.asyncapi import (
    _wire_type_to_class_name as _wire_type_to_class,
)

_BANNER = "<!-- Generated by `task schemas`. Do not edit. -->"

_INTRO = f"""\
gymrat writes two append-only JSONL log files during a session:
a session log at `{SESSION_LOG_ADDRESS}`
and a supervisor log at `{SUPERVISOR_LOG_ADDRESS}`,
where `<ms>` is the launch time in milliseconds since the Unix epoch.
Both files carry one JSON object per line, with snake_case keys.
The `at` field is an integer: nanoseconds since the Unix epoch.
Optional fields are absent rather than `null`;
a field marked required may still be `null` when the schema allows it.
The `schema` field appears on the first line only."""

_PROSE_WIDTH = 100

_SESSION_WIRE_ORDER = [
    "session",
    "baseline",
    "iteration",
    "keep",
    "discard",
    "hook",
    "finalize",
    "stop",
    "command",
]

_SUPERVISOR_WIRE_ORDER = [
    "thinking_update",
    "tool_start",
    "tool_progress",
    "tool_end",
    "text_delta",
    "usage_update",
    "cap",
    "model_phase",
    "launch",
    "turn_end",
    "follow_up",
    "compaction",
]


# ---------------------------------------------------------------------------
# Type and value rendering
# ---------------------------------------------------------------------------


def _docstring_first_line(class_name: str, schema_def: dict[str, Any]) -> str:
    cls = _MODEL_BY_NAME.get(class_name)
    if cls is not None:
        return _model_docstring_first_line(cls)
    description = schema_def.get("description")
    return str(description) if description else class_name


def _ref_name(ref: str) -> str:
    return ref.rsplit("/", maxsplit=1)[-1]


def _ref_link(ref: str) -> str:
    ref_name = _ref_name(ref)
    return f"[{ref_name}](#{ref_name.lower()})"


def _render_any_of_variant(variant: dict[str, Any]) -> str | None:
    """Render one ``anyOf`` variant, returning ``None`` if not recognized."""
    if "$ref" in variant:
        return _ref_link(str(variant["$ref"]))
    if variant.get("type") == "null":
        return "null"
    if "const" in variant:
        return f"`{json.dumps(variant['const'])}`"
    if "type" in variant:
        return str(variant["type"])
    return None


def _render_typed_prop(type_val: str, prop: dict[str, Any]) -> str:
    """Render a property whose ``type`` key is already resolved."""
    if type_val == "array":
        items = prop.get("items", {})
        if isinstance(items, dict) and "type" in items:
            return f"array of {items['type']}"
        return "array"
    if type_val == "object":
        additional = prop.get("additionalProperties")
        if isinstance(additional, dict) and "$ref" in additional:
            return f"object (values: {_ref_link(str(additional['$ref']))})"
        return "object"
    return type_val


def _render_type(prop: dict[str, Any]) -> str:
    """Render a JSON Schema property to a human-readable type string."""
    if "$ref" in prop:
        return _ref_link(str(prop["$ref"]))

    if "const" in prop:
        return f"`{json.dumps(prop['const'])}`"

    if "enum" in prop:
        values = prop["enum"]
        return " \\| ".join(f"`{json.dumps(v)}`" for v in values)

    if "anyOf" in prop:
        parts = [
            rendered
            for v in prop["anyOf"]
            if isinstance(v, dict) and (rendered := _render_any_of_variant(v)) is not None
        ]
        return " \\| ".join(parts)

    type_val = prop.get("type")
    if type_val is not None:
        return _render_typed_prop(str(type_val), prop)

    return "object"


# ---------------------------------------------------------------------------
# Prose wrapping
# ---------------------------------------------------------------------------


def _wrap_line(line: str) -> str:
    """Wrap a single prose line, leaving Markdown list markers and structure lines intact."""
    if line.startswith("- "):
        return textwrap.fill(line, width=_PROSE_WIDTH, initial_indent="", subsequent_indent="  ")
    if line.startswith(("|", "#", "<!--")):
        return line
    return textwrap.fill(line, width=_PROSE_WIDTH)


def _wrap_prose(text: str) -> str:
    """Wrap prose paragraphs at the configured width."""
    paragraphs = text.split("\n\n")
    wrapped = [
        "\n".join(_wrap_line(line) for line in paragraph.split("\n")) for paragraph in paragraphs
    ]
    return "\n\n".join(wrapped)


# ---------------------------------------------------------------------------
# Field tables and nested subsections
# ---------------------------------------------------------------------------


def _build_field_table(
    schema_def: dict[str, Any],
) -> str:
    """Build a Markdown field table for one ``$defs`` entry."""
    props: dict[str, dict[str, Any]] = schema_def.get("properties", {})
    required_set: set[str] = set(schema_def.get("required", []))

    rows: list[str] = [
        "| Name | Type | Status | Description |",
        "| --- | --- | --- | --- |",
    ]

    for field_name, field_schema in props.items():
        if not isinstance(field_schema, dict):
            continue
        type_str = _render_type(field_schema)
        is_const = "const" in field_schema
        status = "required" if field_name in required_set or is_const else "optional"
        description = str(field_schema.get("description", ""))
        rows.append(f"| `{field_name}` | {type_str} | {status} | {description} |")

    return "\n".join(rows)


def _nested_defs_for(
    schema_def: dict[str, Any],
    defs: dict[str, dict[str, Any]],
    wire_to_class: dict[str, str],
) -> list[str]:
    """Return ``$defs`` entries that are nested objects, not union members."""
    union_classes = set(wire_to_class.values())
    props: dict[str, dict[str, Any]] = schema_def.get("properties", {})
    candidate_refs = [
        ref_name
        for field_schema in props.values()
        if isinstance(field_schema, dict)
        for ref_name in _collect_refs(field_schema)
    ]

    nested: list[str] = []
    for ref_name in candidate_refs:
        if ref_name in defs and ref_name not in union_classes and ref_name not in nested:
            nested.append(ref_name)

    return nested


def _collect_refs(schema: dict[str, Any]) -> list[str]:
    """Collect all ``$ref`` target names from a property schema."""
    refs: list[str] = []
    if "$ref" in schema:
        refs.append(_ref_name(str(schema["$ref"])))
    if "anyOf" in schema:
        refs.extend(
            _ref_name(str(variant["$ref"]))
            for variant in schema["anyOf"]
            if isinstance(variant, dict) and "$ref" in variant
        )
    additional = schema.get("additionalProperties")
    if isinstance(additional, dict) and "$ref" in additional:
        refs.append(_ref_name(str(additional["$ref"])))
    return refs


def _append_nested_sections(
    parts: list[str],
    nested_names: list[str],
    defs: dict[str, dict[str, Any]],
    wire_to_class: dict[str, str],
    rendered: set[str],
) -> None:
    """Render each nested subsection and append the non-empty ones to ``parts``."""
    for name in nested_names:
        nested_md = _render_nested_subsection(name, defs, wire_to_class, rendered)
        if nested_md:
            parts.append("")
            parts.append(nested_md)


def _render_type_block(
    heading: str,
    class_name: str,
    defs: dict[str, dict[str, Any]],
    wire_to_class: dict[str, str],
    rendered: set[str],
) -> list[str]:
    """Build a heading/doc/table block, with nested subsections appended.

    Args:
        heading: The Markdown heading line, including its `#` prefix.
        class_name: The schema class to render.
        defs: All schema definitions, keyed by class name.
        wire_to_class: Mapping from wire type to class name.
        rendered: Class names already rendered as nested subsections; mutated
            in place as nested subsections are appended.

    Returns:
        The heading, doc, and field-table lines, followed by any nested
        subsections.
    """
    schema_def = defs[class_name]
    doc = _docstring_first_line(class_name, schema_def)
    parts: list[str] = [heading, "", doc, "", _build_field_table(schema_def)]
    nested = _nested_defs_for(schema_def, defs, wire_to_class)
    _append_nested_sections(parts, nested, defs, wire_to_class, rendered)
    return parts


def _render_nested_subsection(
    class_name: str,
    defs: dict[str, dict[str, Any]],
    wire_to_class: dict[str, str],
    rendered: set[str],
) -> str:
    """Render a #### subsection for a nested object, recursing into its own nested refs."""
    if class_name in rendered or class_name not in defs:
        return ""
    rendered.add(class_name)

    block = _render_type_block(f"#### `{class_name}`", class_name, defs, wire_to_class, rendered)
    return "\n".join(block)


# ---------------------------------------------------------------------------
# Log-section rendering
# ---------------------------------------------------------------------------


def _render_log_section(
    heading: str,
    wire_order: list[str],
    defs: dict[str, dict[str, Any]],
) -> str:
    """Render a ## log section with ### subsections per wire type."""
    wire_to_class = _wire_type_to_class(defs)
    parts: list[str] = []
    parts.append(f"## {heading}")
    parts.append("")

    rendered_nested: set[str] = set()

    for wire_type in wire_order:
        class_name = wire_to_class.get(wire_type)
        if class_name is None:
            continue

        block = _render_type_block(
            f"### `{wire_type}`", class_name, defs, wire_to_class, rendered_nested
        )
        parts.extend(block)
        parts.append("")

    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Readers section
# ---------------------------------------------------------------------------


def _render_readers_section(
    readers: dict[str, ReaderSpec],
) -> str:
    """Render the ## Readers section listing operations and their types."""
    parts: list[str] = []
    parts.append("## Readers")
    parts.append("")
    parts.append(
        "Each reader operation consumes a subset of record or event types from one log file."
    )
    parts.append("")

    for op_name, spec in readers.items():
        types_str = ", ".join(f"`{t}`" for t in spec.types)
        parts.append(
            f"- **{op_name}** (channel: `{spec.channel}`): {spec.description} Types: {types_str}"
        )

    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Top-level orchestration
# ---------------------------------------------------------------------------


def render_reference(
    schemas: tuple[dict[str, Any], dict[str, Any]],
    readers: dict[str, ReaderSpec],
) -> str:
    """Build a Markdown reference document from JSON schemas and reader specs.

    Args:
        schemas: The (session_log, supervisor_log) tuple returned by render_json_schemas().
        readers: The READERS dict from asyncapi.py.

    Returns:
        The rendered Markdown string with word-wrapped prose.
    """
    session_log, supervisor_log = schemas
    session_defs: dict[str, dict[str, Any]] = session_log.get("$defs", {})
    supervisor_defs: dict[str, dict[str, Any]] = supervisor_log.get("$defs", {})

    sections: list[str] = []
    sections.append(_BANNER)
    sections.append("")
    sections.append("# Event Reference")
    sections.append("")
    sections.append(_INTRO)
    sections.append("")
    sections.append(
        _render_log_section("Session Log", _SESSION_WIRE_ORDER, session_defs),
    )
    sections.append(
        _render_log_section(
            "Supervisor Log",
            _SUPERVISOR_WIRE_ORDER,
            supervisor_defs,
        ),
    )
    sections.append(_render_readers_section(readers))

    raw = "\n".join(sections)
    wrapped = _wrap_prose(raw)

    result = "\n".join(line.rstrip() for line in wrapped.split("\n"))
    return result.rstrip("\n") + "\n"
