"""Pure statistics helpers: descriptive summaries and a paired permutation test.

Nothing here performs I/O, formats output, or reads configuration. Beyond the
standard library, only :data:`~gymrat.model.Direction` is imported at module
level, as a lightweight type alias.

``compute_half_range`` treats empty input as a programming error — callers are
expected to have samples — and raises a plain :class:`ValueError` rather than a
domain error.  ``combine_geomean`` accepts empty input and returns all-zero
fields.

``sign_flip_permutation_test`` is an exact sign-flip permutation test over
index-paired samples. It pairs ``x`` and ``y`` positionally over the shorter
input and asks whether the paired median percent delta could plausibly arise
under the null hypothesis of no effect. Under that null a paired observation is
exchangeable with its partner, so the null distribution is generated by flipping
the sign of each pair's difference: enumerated exhaustively when the ``2**n``
sign-flip space over the ``n`` differing pairs fits the resample budget (tied
pairs are held fixed), and sampled with a fixed seed above it. Either way the
reported p-value is deterministic for a given input. ``numpy`` and ``scipy`` are
imported inside that function, so importing this module never pulls them in.
"""

import math
import statistics
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from typing import Literal

from gymrat.model import Direction

__all__ = [
    "PERMUTATION_SEED",
    "RESAMPLE_BUDGET",
    "GeomeanCombination",
    "RatioExclusion",
    "RatioOutcome",
    "SignificanceResult",
    "combine_geomean",
    "compute_half_range",
    "count_nonzero_pairs",
    "normalize_ratio",
    "percent_delta",
    "sign_flip_permutation_test",
]

# ---------------------------------------------------------------------------
# Descriptive statistics
# ---------------------------------------------------------------------------

type RatioExclusion = Literal["undefined-ratio", "infinite-rho"]
"""Why a percent delta could not be normalized into a usable ratio rho."""


@dataclass(frozen=True, slots=True)
class RatioOutcome:
    """A normalized ratio rho, or the reason it was excluded.

    Exactly one of two states holds. A usable rho has ``rho`` set and ``reason``
    ``None``; an exclusion has ``rho`` ``None`` and ``reason`` naming the cause.
    A caller distinguishes them by testing ``rho is not None``.

    Attributes:
        rho: The usable ratio, or ``None`` when the delta was excluded.
        reason: The exclusion cause, or ``None`` when ``rho`` is usable.
    """

    rho: float | None
    reason: RatioExclusion | None


@dataclass(frozen=True, slots=True)
class GeomeanCombination:
    """The geometric-mean combination of a set of included entries.

    This is a pure math result local to this module — not the richer
    :class:`gymrat.model.GeomeanResult`.

    Attributes:
        value: The combined percent change, ``(exp(mean(ln rho)) - 1) * 100``.
        n: The number of entries combined.
        band: The quadrature-combined noise band,
            ``sqrt(sum(noise_pct**2)) / n``.
    """

    value: float
    n: int
    band: float


def compute_half_range(values: Sequence[float]) -> float:
    """Return half the span ``(max - min) / 2`` of ``values``.

    A single non-finite sample poisons the whole result: it never drops a
    sample and never returns ±infinity, so any NaN or ±infinity among the
    samples yields the NaN undefined-measurement sentinel.

    Args:
        values: The samples to summarize. Must be non-empty.

    Returns:
        Half the span over finite samples, or ``float("nan")`` when any sample
        is non-finite.

    Raises:
        ValueError: If ``values`` is empty.
    """
    if not values:
        msg = "compute_half_range requires at least one sample; got an empty sequence"
        raise ValueError(msg)
    if any(not math.isfinite(sample) for sample in values):
        return math.nan
    return (max(values) - min(values)) / 2.0


def percent_delta(reference: float, value: float) -> float:
    """Return the percent change of ``value`` against ``reference``'s magnitude.

    Dividing by the magnitude keeps the sign tied to the direction the value
    moved: a negative reference rising toward zero is an increase, and one
    dropping further below zero is a decrease. When the reference is zero the
    ratio is undefined, so the caller decides how to treat the ``NaN``.

    Args:
        reference: The value the change is measured from.
        value: The value compared against ``reference``.

    Returns:
        ``(value - reference) / abs(reference) * 100``, ``0.0`` when both are
        zero, or ``NaN`` when only ``reference`` is zero.
    """
    if reference == 0:
        return 0.0 if value == 0 else math.nan
    return (value - reference) / abs(reference) * 100


def normalize_ratio(delta: float, direction: Direction) -> RatioOutcome:
    """Normalize a percent ``delta`` into a ratio rho for the given direction.

    For ``"lower"``, ``rho = 1 + delta / 100``. For ``"higher"``,
    ``rho = 1 / (1 + delta / 100)``. A rho that is not strictly positive and
    finite cannot be combined in log space, so it is reported as an exclusion.

    Args:
        delta: The percent delta to normalize.
        direction: Whether a lower or higher raw value is the improvement.

    Returns:
        A :class:`RatioOutcome` carrying a usable rho, or ``"undefined-ratio"``
        when ``delta`` is NaN, or ``"infinite-rho"`` when the resulting rho is
        non-positive or non-finite.
    """
    if math.isnan(delta):
        return RatioOutcome(rho=None, reason="undefined-ratio")
    factor = 1.0 + delta / 100.0
    rho = factor
    if direction == "higher":
        # A zero factor would divide by zero; route it to the infinite-rho
        # exclusion below instead of raising.
        rho = 1.0 / factor if factor != 0.0 else math.inf
    if rho <= 0.0 or not math.isfinite(rho):
        return RatioOutcome(rho=None, reason="infinite-rho")
    return RatioOutcome(rho=rho, reason=None)


def combine_geomean(entries: Sequence[tuple[float, float]]) -> GeomeanCombination:
    """Combine included ``(rho, noise_pct)`` entries via the geometric mean.

    The combined value is the geometric mean of the ratios expressed as a
    percent change; the band combines per-entry noise in quadrature.

    Args:
        entries: The included entries, each a ``(rho, noise_pct)`` pair. Every
            ``rho`` must be strictly positive.

    Returns:
        A :class:`GeomeanCombination`. Empty input yields all-zero fields; a
        single entry yields that rho as a percent change with its own noise as
        the band.
    """
    n = len(entries)
    if n == 0:
        return GeomeanCombination(value=0.0, n=0, band=0.0)
    value = (statistics.geometric_mean(rho for rho, _ in entries) - 1.0) * 100.0
    band = math.hypot(*(noise_pct for _, noise_pct in entries)) / n
    return GeomeanCombination(value=value, n=n, band=band)


# ---------------------------------------------------------------------------
# Paired permutation test
# ---------------------------------------------------------------------------

# The permutation needs at least two paired observations; a single pair admits
# only the trivial sign flip and carries no null spread to test against.
_MIN_PAIRS = 2

RESAMPLE_BUDGET = 9999
"""Upper bound on sign-flip resamples.

When the exact null space ``2**pairs`` is at most this budget, every sign flip
is enumerated (exact test); above it, this many Monte Carlo resamples are drawn.
The value brackets the exact/Monte Carlo seam at ``pairs == 13``: ``2**13 ==
8192`` still enumerates exactly, while ``2**14 == 16384`` crosses into sampling.
"""

PERMUTATION_SEED = 12345
"""Fixed RNG seed for the Monte Carlo path, making sampled p-values reproducible."""


@dataclass(frozen=True, slots=True)
class SignificanceResult:
    """The outcome of a paired significance test.

    Attributes:
        p: The two-sided p-value, always within ``[0.0, 1.0]``.
        n: The number of paired entries whose two values differ.  Tied
            pairs (equal values) are held fixed on both sides — they
            contribute to medians under every rearrangement but are not
            sign-flipped.
    """

    p: float
    n: int


def _partition_pairs(
    x: Sequence[float], y: Sequence[float]
) -> tuple[list[float], list[float], list[float], list[float]]:
    """Separate tied (equal values) and differing pairs, paired over the shorter input.

    Args:
        x: The first value of each pair.
        y: The second value of each pair.

    Returns:
        A tuple ``(tied_x, tied_y, diff_x, diff_y)`` partitioning the pairs.
    """
    tied_x: list[float] = []
    tied_y: list[float] = []
    diff_x: list[float] = []
    diff_y: list[float] = []
    for xi, yi in zip(x, y, strict=False):
        if xi == yi:
            tied_x.append(xi)
            tied_y.append(yi)
        else:
            diff_x.append(xi)
            diff_y.append(yi)
    return tied_x, tied_y, diff_x, diff_y


def count_nonzero_pairs(x: Sequence[float], y: Sequence[float]) -> tuple[int, int]:
    """Pair ``x`` and ``y`` positionally over the shorter input and count differing pairs.

    Shared by every paired significance test: each pairs ``x[i]`` with ``y[i]``
    for ``i`` below the shorter input's length.  A pair is tied when its values
    compare equal (``x[i] == y[i]``) and differing otherwise, so a pair of equal
    infinities is tied and a pair holding a NaN always differs.  The caller holds
    tied pairs fixed on both sides of the test rather than dropping them.

    Args:
        x: The first sample.
        y: The second sample, paired positionally with ``x``.

    Returns:
        A ``(m, n)`` pair: ``m`` is the number of positions paired (the shorter
        input's length), and ``n`` is how many of those pairs have values that
        differ (``x[i] != y[i]``).
    """
    tied_x, _, diff_x, _ = _partition_pairs(x, y)
    return len(tied_x) + len(diff_x), len(diff_x)


def _median_delta(
    tied_x: list[float],
    tied_y: list[float],
    baseline: Sequence[float],
    candidate: Sequence[float],
) -> float:
    return percent_delta(
        statistics.median(tied_x + list(baseline)), statistics.median(tied_y + list(candidate))
    )


def _make_statistic(
    tied_x: list[float],
    tied_y: list[float],
    observed: float,
) -> Callable[[Sequence[float], Sequence[float]], float]:
    """Build the test statistic closure for scipy's permutation_test.

    An undefined delta (a zero baseline median) becomes infinity signed like
    ``observed``, so scipy's null tally counts it on the correct tail.

    Args:
        tied_x: Baseline values of the tied (equal-value) pairs, held fixed.
        tied_y: Candidate values of the tied (equal-value) pairs, held fixed.
        observed: The delta the samples produced in their original order.

    Returns:
        The statistic scipy evaluates on each rearrangement of the differing pairs.
    """

    def statistic(baseline: Sequence[float], candidate: Sequence[float]) -> float:
        delta = _median_delta(tied_x, tied_y, baseline, candidate)
        if math.isnan(delta):
            return math.copysign(math.inf, observed)
        return delta

    return statistic


def sign_flip_permutation_test(x: Sequence[float], y: Sequence[float]) -> SignificanceResult:
    """Run a two-sided sign-flip permutation test on index-paired samples.

    The inputs are paired positionally over the shorter of the two: ``x[i]`` is
    compared with ``y[i]`` for ``i < min(len(x), len(y))``, and trailing entries
    of the longer input are ignored. The reported ``n`` counts only pairs whose
    two values differ.

    Tied pairs (equal values) are held fixed on both sides: they contribute
    to the median under every rearrangement but are never sign-flipped, so the
    effective null space is ``2**n`` where ``n`` is the differing-pair count.

    The test statistic is the median percent delta of the paired slices,
    ``100 * (median(y) - median(x)) / abs(median(x))``; its permutation null
    distribution comes from flipping the sign of each differing pair's
    difference. When ``2**n`` fits :data:`RESAMPLE_BUDGET` the enumeration is
    exact; otherwise :data:`RESAMPLE_BUDGET` Monte Carlo resamples are drawn from
    a generator seeded with :data:`PERMUTATION_SEED`. Both paths are
    deterministic for a given input.

    Args:
        x: The baseline sample.
        y: The candidate sample, paired positionally with ``x``.

    Returns:
        The p-value and the count of differing pairs used.
    """
    tied_x, tied_y, diff_x, diff_y = _partition_pairs(x, y)
    n = len(diff_x)
    if n < _MIN_PAIRS:
        return SignificanceResult(p=1.0, n=n)

    observed = _median_delta(tied_x, tied_y, diff_x, diff_y)
    if not math.isfinite(observed):
        return SignificanceResult(p=1.0, n=n)

    # Lazy import: tests/test_import_latency.py guards the package's startup cost.
    import numpy as np  # noqa: PLC0415
    from scipy.stats import permutation_test  # noqa: PLC0415

    # scipy enumerates all 2**n sign flips itself whenever they fit the budget.
    result = permutation_test(
        (diff_x, diff_y),
        _make_statistic(tied_x, tied_y, observed),
        permutation_type="samples",
        alternative="two-sided",
        vectorized=False,
        n_resamples=RESAMPLE_BUDGET,
        rng=np.random.default_rng(PERMUTATION_SEED),
    )
    return SignificanceResult(p=float(result.pvalue), n=n)
