"""Table subpackage: structured line types and rendering for comparison tables."""

from gymrat.report.table.render import (
    CELL_GUTTER,
    GROUP_INDENT,
    METRIC_COLUMN_HEADER,
    METRIC_COLUMN_MIN,
    VALUE_COLUMN_MIN,
    VERDICT_COLUMN_MIN,
    AggregateColumnCell,
    AggregateLine,
    AggregateRow,
    AggregateRows,
    BlankLine,
    BodyLine,
    BorderLine,
    GroupLine,
    HeaderLine,
    MetricLine,
    RuleLine,
    StyledSpan,
    TitleLine,
    ValueWidths,
    VerdictParts,
    VerdictWidths,
    aggregate_label_lengths,
    band_field,
    compute_column_width,
    geomean_column_cell,
    group_metric_cell,
    header_metric_cell,
    indented_section_label,
    join_value_cell,
    join_verdict_cell,
    plan_body,
    render_body,
    section_annotation,
    style_verdict_cell,
    value_widths,
    verdict_parts,
    verdict_widths,
    widest_header_label,
)
from gymrat.report.table.render import __all__ as __all__
