"""Report rendering package.

Public style, formatting, and rendering-input contracts are re-exported here so
callers can import them from :mod:`gymrat_py.report` without reaching into
submodules.
"""

from gymrat_py.report.format import (
    GEOMEAN_LABEL,
    MIN_BAND_N,
    MIN_WILCOXON_N,
    QUIET_VERDICTS,
    VERDICT_GLOSSES,
    DisplayClass,
    MetricHighlight,
    VerdictCounts,
    count_verdicts,
    display_class,
    footer_lines,
    format_delta,
    format_evidence,
    format_noise_band_value,
    format_pair_count,
    format_value,
    geomean_scope_label,
    geomean_value_style,
    get_glyph,
    scoped_geomean_label,
    select_highlights,
    verdict_summary_parts,
)
from gymrat_py.report.style import (
    AGGREGATE_LABEL_STYLE,
    GROUP_LABEL_STYLE,
    LABEL_DISPLAY_WIDTH,
    VARIANT_NAME_STYLE,
    VERDICT_STYLES,
    format_hint_label,
    highlight_inline_code,
    make_capture_console,
    render_lines,
    shorten_label,
    truncate_labels,
)
from gymrat_py.report.types import (
    CandidateComparison,
    CandidateMetric,
    ComparisonResult,
    FailOnCondition,
    GeomeanFailOn,
    MeasurementResult,
    MetricComparison,
    MetricComparisons,
    MetricMeasurement,
    MetricMeasurements,
    RegressedFailOn,
    ReportOptions,
    WorktreeCleanupOutcome,
)

__all__ = [
    "AGGREGATE_LABEL_STYLE",
    "GEOMEAN_LABEL",
    "GROUP_LABEL_STYLE",
    "LABEL_DISPLAY_WIDTH",
    "MIN_BAND_N",
    "MIN_WILCOXON_N",
    "QUIET_VERDICTS",
    "VARIANT_NAME_STYLE",
    "VERDICT_GLOSSES",
    "VERDICT_STYLES",
    "CandidateComparison",
    "CandidateMetric",
    "ComparisonResult",
    "DisplayClass",
    "FailOnCondition",
    "GeomeanFailOn",
    "MeasurementResult",
    "MetricComparison",
    "MetricComparisons",
    "MetricHighlight",
    "MetricMeasurement",
    "MetricMeasurements",
    "RegressedFailOn",
    "ReportOptions",
    "VerdictCounts",
    "WorktreeCleanupOutcome",
    "count_verdicts",
    "display_class",
    "footer_lines",
    "format_delta",
    "format_evidence",
    "format_hint_label",
    "format_noise_band_value",
    "format_pair_count",
    "format_value",
    "geomean_scope_label",
    "geomean_value_style",
    "get_glyph",
    "highlight_inline_code",
    "make_capture_console",
    "render_lines",
    "scoped_geomean_label",
    "select_highlights",
    "shorten_label",
    "truncate_labels",
    "verdict_summary_parts",
]
