"""Markdown reference document generation from JSON schemas and readers.

``render_reference(schemas, readers)`` takes the two JSON Schema dicts from
``render_json_schemas()`` and the ``READERS`` dict from ``asyncapi.py``,
returning a Markdown document with a generated-file banner, per-log sections,
per-record/event subsections with field tables, nested-object subsections,
and a closing Readers section.
"""

import re

import pytest

from gymrat.event_docs.asyncapi import READERS, SESSION_LOG_ADDRESS, SUPERVISOR_LOG_ADDRESS
from gymrat.event_docs.json_schema import render_json_schemas
from gymrat.session.paths import SESSION_LOG_NAME, supervisor_log_name


def _render() -> str:
    from gymrat.event_docs.reference import render_reference

    schemas = render_json_schemas()
    return render_reference(schemas, READERS)


def _intro(md: str) -> str:
    intro_end = md.find("\n## ")
    return md[:intro_end]


def _section_for_type(md: str, wire_type: str) -> str:
    start = md.find(f"\n### `{wire_type}`\n")
    next_heading = md.find("\n### ", start + 1)
    return md[start:next_heading] if next_heading != -1 else md[start:]


def _readers_section(md: str) -> str:
    readers_start = md.find("## Readers")
    return md[readers_start:]


# ---------------------------------------------------------------------------
# banner
# ---------------------------------------------------------------------------


def test_render_reference_when_called_does_start_with_generated_file_banner():
    md = _render()

    first_line = md.split("\n")[0]

    assert "Generated by" in first_line or "generated by" in first_line
    assert "task schemas" in first_line


# ---------------------------------------------------------------------------
# introduction
# ---------------------------------------------------------------------------


def test_render_reference_when_called_does_include_introduction_after_banner():
    md = _render()

    assert "one JSON object per line" in md
    assert "snake_case" in md
    assert "nanoseconds" in md.lower()


def test_render_reference_when_called_does_name_log_files_from_asyncapi_channel_constants():
    md = _render()

    intro = _intro(md)

    assert SESSION_LOG_ADDRESS in intro
    assert SUPERVISOR_LOG_ADDRESS in intro


def test_render_reference_when_called_does_distinguish_absent_optional_from_nullable_required():
    md = _render()

    intro = _intro(md)

    assert "absent" in intro.lower()
    assert "null" in intro.lower()
    assert "required" in intro.lower()


# ---------------------------------------------------------------------------
# log sections — ## Session Log and ## Supervisor Log
# ---------------------------------------------------------------------------


def test_render_reference_when_called_does_have_session_and_supervisor_log_sections():
    md = _render()

    assert "\n## Session Log\n" in md or "\n## Session Log \n" in md
    assert "\n## Supervisor Log\n" in md or "\n## Supervisor Log \n" in md


# ---------------------------------------------------------------------------
# per-record/event ### sections — one per union member, in declared order
# ---------------------------------------------------------------------------


_SESSION_WIRE_ORDER = [
    "session",
    "baseline",
    "iteration",
    "keep",
    "discard",
    "hook",
    "finalize",
    "stop",
    "command",
]

_SUPERVISOR_WIRE_ORDER = [
    "thinking_update",
    "tool_start",
    "tool_progress",
    "tool_end",
    "text_delta",
    "usage_update",
    "cap",
    "model_phase",
    "launch",
    "turn_end",
    "follow_up",
    "compaction",
]


@pytest.mark.parametrize(
    "wire_type",
    [pytest.param(wt, id=wt) for wt in _SESSION_WIRE_ORDER],
)
def test_render_reference_when_called_does_have_section_for_session_record_type(
    wire_type: str,
):
    md = _render()

    assert f"\n### `{wire_type}`\n" in md


@pytest.mark.parametrize(
    "wire_type",
    [pytest.param(wt, id=wt) for wt in _SUPERVISOR_WIRE_ORDER],
)
def test_render_reference_when_called_does_have_section_for_supervisor_event_type(
    wire_type: str,
):
    md = _render()

    assert f"\n### `{wire_type}`\n" in md


def _assert_sections_in_declared_order(md: str, wire_order: list[str], label: str) -> None:
    positions = []
    for wire_type in wire_order:
        pos = md.find(f"\n### `{wire_type}`\n")
        assert pos != -1, f"missing section for {wire_type}"
        positions.append(pos)

    assert positions == sorted(positions), f"{label} sections out of order: {wire_order}"


def test_render_reference_when_called_does_order_session_sections_per_union_declaration():
    md = _render()

    _assert_sections_in_declared_order(md, _SESSION_WIRE_ORDER, "session")


def test_render_reference_when_called_does_order_supervisor_sections_per_union_declaration():
    md = _render()

    _assert_sections_in_declared_order(md, _SUPERVISOR_WIRE_ORDER, "supervisor")


# ---------------------------------------------------------------------------
# field tables — iteration and launch as representative types
# ---------------------------------------------------------------------------


def _assert_has_field_rows(section: str, fields: list[str], label: str) -> None:
    for field in fields:
        assert f"| `{field}`" in section or f"| {field}" in section, (
            f"missing field row for '{field}' in {label}"
        )


def test_render_reference_when_called_does_have_iteration_field_rows():
    md = _render()

    iteration_section = _section_for_type(md, "iteration")

    expected_fields = [
        "seq",
        "samples",
        "metrics",
        "confirm",
        "primary",
        "outcome",
        "target_reached",
        "duration_ms",
        "measured_tree",
    ]
    _assert_has_field_rows(iteration_section, expected_fields, "iteration section")


def test_render_reference_when_called_does_have_launch_field_rows():
    md = _render()

    launch_section = _section_for_type(md, "launch")

    expected_fields = [
        "schema",
        "session_id",
        "head_sha",
        "dirty",
        "max_minutes",
        "kickoff_summary",
    ]
    _assert_has_field_rows(launch_section, expected_fields, "launch section")


# ---------------------------------------------------------------------------
# field table structure — columns: name, type, required/optional, description
# ---------------------------------------------------------------------------


def test_render_reference_when_called_does_have_table_header_with_four_columns():
    md = _render()

    table_header_pattern = re.compile(
        r"\| *Name *\| *Type *\| *Status *\| *Description *\|"
        r"|\| *name *\| *type *\| *required/optional *\| *description *\|",
        re.IGNORECASE,
    )

    assert table_header_pattern.search(md), "field table header not found"


def _field_row(section: str, field: str) -> str:
    rows = [line for line in section.split("\n") if field in line and "|" in line]
    assert len(rows) >= 1
    return rows[0]


def test_render_reference_when_called_does_mark_required_fields_as_required():
    md = _render()

    iteration_section = _section_for_type(md, "iteration")

    assert "required" in _field_row(iteration_section, "seq").lower()


def test_render_reference_when_called_does_mark_optional_fields_as_optional():
    md = _render()

    iteration_section = _section_for_type(md, "iteration")

    assert "optional" in _field_row(iteration_section, "duration_ms").lower()


def test_render_reference_when_called_does_mark_const_type_discriminator_as_required():
    md = _render()

    tool_start_section = _section_for_type(md, "tool_start")
    type_row = [
        line for line in tool_start_section.split("\n") if "| `type`" in line and "|" in line
    ]

    assert len(type_row) >= 1, "no type row found in tool_start section"
    assert "required" in type_row[0].lower(), (
        f"expected const type to be marked required, got: {type_row[0]!r}"
    )


# ---------------------------------------------------------------------------
# nested object subsections
# ---------------------------------------------------------------------------


def test_render_reference_when_called_does_have_nested_object_subsections():
    md = _render()

    nested_objects = ["config", "samples", "primary", "confirm", "checks", "dirty"]
    found = 0
    for name in nested_objects:
        if "\n#### " in md and name in md:
            found += 1

    assert found >= 3, f"expected at least 3 nested object #### subsections, found {found}"


# ---------------------------------------------------------------------------
# readers section
# ---------------------------------------------------------------------------


def test_render_reference_when_called_does_have_readers_section():
    md = _render()

    assert "\n## Readers\n" in md or "\n## Readers \n" in md


def test_render_reference_when_called_does_list_all_four_reader_operations():
    md = _render()

    readers_section = _readers_section(md)

    for op_name in ("fold-session", "status-history", "supervisor-guard", "dashboard"):
        assert op_name in readers_section, (
            f"reader operation '{op_name}' not found in Readers section"
        )


def test_render_reference_when_called_does_show_reader_descriptions():
    md = _render()

    readers_section = _readers_section(md)

    for op_name, spec in READERS.items():
        assert spec.description, f"reader {op_name!r} has no description"
        assert spec.description in readers_section, (
            f"description for reader {op_name!r} not found in Readers section"
        )


# ---------------------------------------------------------------------------
# formatting — wrapping, trailing newline, no trailing spaces
# ---------------------------------------------------------------------------


def test_render_reference_when_called_does_wrap_prose_at_100_columns():
    md = _render()

    for line in md.split("\n"):
        is_table = line.lstrip().startswith("|")
        is_html_comment = line.lstrip().startswith("<!--")
        if is_table or is_html_comment:
            continue
        assert len(line) <= 100, f"line exceeds 100 columns ({len(line)} chars): {line[:120]!r}"


def test_render_reference_when_called_does_end_with_single_trailing_newline():
    md = _render()

    assert md.endswith("\n")
    assert not md.endswith("\n\n")


def test_render_reference_when_called_does_have_no_trailing_spaces():
    md = _render()

    for i, line in enumerate(md.split("\n"), 1):
        assert line == line.rstrip(" "), f"line {i} has trailing spaces: {line!r}"


# ---------------------------------------------------------------------------
# asyncapi addresses derive from path naming helpers
# ---------------------------------------------------------------------------


def test_session_log_address_when_accessed_does_end_with_session_log_name():
    assert SESSION_LOG_ADDRESS.endswith(SESSION_LOG_NAME)


def test_supervisor_log_address_when_accessed_does_match_supervisor_log_name_pattern():
    assert SUPERVISOR_LOG_ADDRESS.endswith(supervisor_log_name("<ms>"))


# ---------------------------------------------------------------------------
# intro prose — file descriptions and timestamp explanation
# ---------------------------------------------------------------------------


def test_render_reference_when_called_does_say_supervisor_log_at():
    md = _render()

    intro = _intro(md)

    assert "a supervisor log at" in intro


def test_render_reference_when_called_does_explain_ms_as_launch_milliseconds():
    md = _render()

    intro = _intro(md)

    assert "milliseconds since the unix epoch" in intro.lower()
    assert "launch" in intro.lower()
